### coupler1
POST http://localhost:4040/coupler1/activate
###
POST http://localhost:4040/coupler1/deactivate
###
GET http://localhost:4040/coupler1

### coupler2
POST http://localhost:4040/coupler2/activate
###
POST http://localhost:4040/coupler2/deactivate
###
GET http://localhost:4040/coupler2

### filter2
POST http://localhost:4040/filter2/activate
###
POST http://localhost:4040/filter2/deactivate
###
GET http://localhost:4040/filter2

### filter1
POST http://localhost:4040/filter1/change/100
###
GET http://localhost:4040/filter1

### combination
POST http://localhost:4040/combination/trigger
