[package]
name = "anabeeb"
version = "0.1.0"
edition = "2024"
authors = ["Sven Meier <sven@meiers.net>"]

[dependencies]
regex = "1"
crossbeam-channel = "0.5"
crokey = { version = "1.2.0", features = ["serde"] }
midir = "0.10.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
schemars = "0.9.0"
rouille = "3"
env_logger = "0.11.8"
log = "0.4.27"
fluidsynth = "0.0.1"
clap = { version = "4", features = ["derive"] }
atty = "0.2.14"
uuid = { version = "1.17.0", features = ["v4"] }

[lib]
name = "anabeeb"
path = "src/lib.rs"

[package.metadata.deb]
revision = "1"
maintainer = "Sven Meier <sven@meiers.net>"
depends = "libfluidsynth3 (>= 2.0.0)"
assets = [
    ["target/release/anabeeb", "usr/bin/", "755"],
]