### coupler1
POST http://localhost:4040/element/coupler1/activate
###
POST http://localhost:4040/element/coupler1/deactivate
###
GET http://localhost:4040/element/coupler1

### coupler2
POST http://localhost:4040/element/coupler2/activate
###
POST http://localhost:4040/element/coupler2/deactivate
###
GET http://localhost:4040/element/coupler2

### filter2
POST http://localhost:4040/element/filter2/activate
###
POST http://localhost:4040/element/filter2/deactivate
###
GET http://localhost:4040/element/filter2

### filter1
POST http://localhost:4040/element/filter1/change/100
###
GET http://localhost:4040/element/filter1

### memory
POST http://localhost:4040/element/memory/change/0
###
POST http://localhost:4040/element/memory/change/1
###
GET http://localhost:4040/element/memory
